# Generated by Django 4.1.3 on 2022-11-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=200, unique=True)),
                ('mime_type', models.CharField(max_length=20)),
                ('media_type', models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Image'), (1, 'Video')])),
                ('x_resolution', models.PositiveIntegerField(default=None, null=True)),
                ('y_resolution', models.PositiveIntegerField(default=None, null=True)),
                ('diff_hash1', models.BigIntegerField(default=None, null=True)),
                ('diff_hash2', models.BigIntegerField(default=None, null=True)),
                ('diff_hash3', models.BigIntegerField(default=None, null=True)),
                ('diff_hash4', models.BigIntegerField(default=None, null=True)),
                ('similar_to', models.ManyToManyField(default=None, related_name='similar_files', to='media_manager.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
                ('recursive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Source Directories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TagAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_tagged', models.BooleanField()),
                ('positive', models.BooleanField(default=True)),
                ('tagged_date', models.DateTimeField(auto_now_add=True)),
                ('certainty', models.DecimalField(decimal_places=3, max_digits=6)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.mediafile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.tag')),
            ],
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(blank=True, through='media_manager.TagAction', to='media_manager.tag'),
        ),
    ]
