# Generated by Django 4.1.3 on 2022-12-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.tag')),
            ],
        ),
    ]
