# Generated by Django 4.0.3 on 2022-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_taggroup_parent_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroup',
            name='parent_tag',
        ),
        migrations.AddField(
            model_name='taggroup',
            name='parent_tags',
            field=models.ManyToManyField(blank=True, default=None, to='media_manager.tag'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_path',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
