# Generated by Django 4.0.3 on 2022-04-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_remove_taggroup_parent_tag_taggroup_parent_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_date', models.DateTimeField(auto_created=True)),
                ('human_tagged', models.BooleanField()),
                ('certainty', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='tags'
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(blank=True, through='media_manager.TagAction', to='media_manager.tag'),
        ),
        migrations.AddField(
            model_name='tagaction',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.mediafile'),
        ),
        migrations.AddField(
            model_name='tagaction',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.tag'),
        ),
    ]
