# Generated by Django 4.0.3 on 2022-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0005_tagaction_alter_mediafile_tags_tagaction_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagaction',
            name='tagged_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
