# Generated by Django 4.1.3 on 2022-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('client_id', models.CharField(max_length=16)),
                ('client_secret', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
